-- regulation-service schema
CREATE DATABASE IF NOT EXISTS food_regulation_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE food_regulation_db;

-- 按照依赖顺序删除表（先删除有外键约束的子表，再删除父表）
DROP TABLE IF EXISTS complaint_handle;
DROP TABLE IF EXISTS complaint;
DROP TABLE IF EXISTS rectification_task;
DROP TABLE IF EXISTS inspection_item;
DROP TABLE IF EXISTS inspection_record;
DROP TABLE IF EXISTS food_enterprise;
DROP TABLE IF EXISTS food_regulator;

CREATE TABLE IF NOT EXISTS food_enterprise (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '对应user-service账号ID',
  enterprise_name VARCHAR(100) NOT NULL COMMENT '企业名称',
  license_no VARCHAR(50) COMMENT '许可证编号',
  address VARCHAR(255) COMMENT '地址',
  principal VARCHAR(50) COMMENT '负责人',
  principal_phone VARCHAR(20) COMMENT '负责人电话',
  regulator_name VARCHAR(50) COMMENT '包保责任人',
  status VARCHAR(20) DEFAULT 'NORMAL' COMMENT 'NORMAL / KEY',
  approval_status VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING / APPROVED / REJECTED',
  approval_comment VARCHAR(255) COMMENT '审核意见',
  approved_by BIGINT COMMENT '审核人ID',
  approved_time DATETIME COMMENT '审核时间',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 1-已删 0-未删',
  UNIQUE KEY uk_enterprise_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='食品企业信息表';

CREATE TABLE IF NOT EXISTS food_regulator (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '对应user-service账号ID',
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  phone VARCHAR(20) COMMENT '手机号',
  role_type VARCHAR(30) NOT NULL COMMENT 'REGULATOR_ADMIN / REGULATOR_ENFORCER',
  jurisdiction_area VARCHAR(100) NOT NULL COMMENT '辖区（省/市/区/街道）',
  status TINYINT DEFAULT 1 COMMENT '1-在岗 0-停用',
  work_id_url VARCHAR(255) COMMENT '工作证件附件',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 1-已删 0-未删',
  UNIQUE KEY uk_regulator_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='监管人员档案表';

CREATE TABLE IF NOT EXISTS inspection_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  enterprise_id BIGINT NOT NULL COMMENT '企业ID',
  inspector_id BIGINT NOT NULL COMMENT '检查人员ID',
  inspection_date DATE COMMENT '检查日期',
  result VARCHAR(20) COMMENT 'PASS / FAIL',
  problem_desc TEXT COMMENT '问题描述',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 1-已删 0-未删'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='监督检查记录表';

CREATE TABLE IF NOT EXISTS inspection_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  inspection_id BIGINT NOT NULL COMMENT '检查记录ID',
  item_name VARCHAR(100) NOT NULL COMMENT '检查项',
  item_result VARCHAR(20) COMMENT 'PASS / FAIL',
  problem_desc TEXT COMMENT '问题描述',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 1-已删 0-未删'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查明细表';

CREATE TABLE IF NOT EXISTS rectification_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  inspection_id BIGINT NOT NULL COMMENT '检查记录ID',
  enterprise_id BIGINT NOT NULL COMMENT '企业ID',
  rectification_desc TEXT COMMENT '整改要求',
  progress VARCHAR(100) COMMENT '整改进度',
  status VARCHAR(20) DEFAULT 'ONGOING' COMMENT 'ONGOING / COMPLETED',
  finish_time DATETIME COMMENT '完成时间',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 1-已删 0-未删'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='整改任务表';

CREATE TABLE IF NOT EXISTS complaint (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  complainant_name VARCHAR(50) COMMENT '投诉人姓名',
  contact VARCHAR(50) COMMENT '联系方式',
  enterprise_id BIGINT NOT NULL COMMENT '企业ID',
  complaint_type VARCHAR(50) COMMENT '投诉类型',
  content TEXT NOT NULL COMMENT '投诉内容',
  status VARCHAR(20) DEFAULT 'SUBMITTED' COMMENT 'SUBMITTED / ASSIGNED / PROCESSING / FEEDBACKED',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 1-已删 0-未删'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公众投诉表';

CREATE TABLE IF NOT EXISTS complaint_handle (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  complaint_id BIGINT NOT NULL COMMENT '投诉ID',
  handler_id BIGINT NOT NULL COMMENT '处理人ID',
  handle_result TEXT COMMENT '处理结果',
  handle_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '处理时间',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 1-已删 0-未删'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投诉处理记录表';
